urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns

from apps.views import index, InstructionsView, SubscribeFormView
from apps.reviews.views import ReviewIndexView, ReviewListView, MoreReviewsView, ReviewFormView
from apps.capabilities.views import CapabilityListView 
from apps.messages.views import OrderFormView, \
                                PartnersView, PartnersDoctorsFormView, PartnersDrugstoresFormView, \
                                PatientsView, PatientsQFormView, PatientsSchoolFormView
from apps.publications.views import ArticleListView, ArticleView, NewsListView, NewsView, PublicationListView, PublicationView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^captcha/', include('captcha.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),
     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),
    # index
    (r'^$', index), 
    # reviews
    url(r'^reviews/$', ReviewIndexView.as_view(), name='reviews_url'),
    url(r'^reviews/patients/$', ReviewListView.as_view(), {'reviewer_type':'patient'}, name='patients_reviews_url'),
    url(r'^reviews/doctors/$', ReviewListView.as_view(), {'reviewer_type':'doctor'}, name='doctors_reviews_url'),
    url(r'^reviews/patients/more/$', MoreReviewsView.as_view(), {'reviewer_type':'patient'}, name='patients_more_url'),
    url(r'^reviews/doctors/more/$', MoreReviewsView.as_view(), {'reviewer_type':'doctor'}, name='doctors_more_url'),
    url(r'^reviews/patients/form/$', ReviewFormView.as_view()),
    url(r'^reviews/doctors/form/$', ReviewFormView.as_view()),
    # capabilities
    url(r'^capabilities/$', CapabilityListView.as_view(), name='capabilities_url'),
    # order form
    url(r'^order/$', OrderFormView.as_view(), name='order_url'),
    # instructions
    url(r'^instructions/$', InstructionsView.as_view(), name='instructions_url'),
    # for_patients
    url(r'^for_patients/$', PatientsView.as_view(), name='patients_url'),
    url(r'^for_patients/q_form/$', PatientsQFormView.as_view(), name='patients_q_url'),
    url(r'^for_patients/school_form/$', PatientsSchoolFormView.as_view(), name='patients_school_url'),
    # for_partners
    url(r'^for_partners/$', PartnersView.as_view(), name='partners_url'),
    url(r'^for_partners/doctors_form/$', PartnersDoctorsFormView.as_view(), name='partners_doctors_url'),
    url(r'^for_partners/clinics_form/$', PartnersDrugstoresFormView.as_view(), name='partners_drugstores_url'),
    # publications
    url(r'^newsboard/$', NewsListView.as_view(), name='news_list_url'),
    url(r'^articles/$', ArticleListView.as_view(), name='article_list_url'),
    url(r'^publications/$', PublicationListView.as_view(), name='publication_list_url'),
    url(r'^publications/(?P<id>\d)/$', PublicationView.as_view(), name='publication_url'),
    url(r'^newsboard/(?P<id>\d)/$', NewsView.as_view(), name='single_news_url'),
    url(r'^articles/(?P<id>\d)/$', ArticleView.as_view(), name='article_url'),
    # subscribe
    url(r'^subscribe/$', SubscribeFormView.as_view(), name='subscribe_url'),
)

urlpatterns += apps_urlpatterns

apps/places/models.py
# coding: utf-8
from datetime import datetime

from django.db import models

class City(models.Model):
    title = models.CharField(
        verbose_name = u'город',
        max_length = 100,
    )
    coordinates_center = models.CharField(
        verbose_name = u'центр координат',
        max_length = 300,
    )
    zoom = models.IntegerField(
        verbose_name = u'зум',
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = u'город'
        verbose_name_plural = u'города'


class Clinic(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'клиника'
        verbose_name_plural = u'клиники'


class Drugstore(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'аптека'
        verbose_name_plural = u'аптеки'


class Lab(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'лаборатория'
        verbose_name_plural = u'лаборатории'
        

class Branch(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'филиал'
        verbose_name_plural = u'филиалы'

apps/reviews/models.py
# -*- coding: utf-8 -*-
import os
from datetime import datetime

from django.db import models

from sorl.thumbnail import ImageField as sorl_ImageField
from pytils.translit import translify

class ImageField(sorl_ImageField, models.ImageField):
    pass

def file_path_reviews(instance, filename):
    return os.path.join('images','reviews', translify(filename).replace(' ', '_') )

REVIEWER_TYPE_CHOICES = (
    ('doctor', u'Врач'),
    ('patient', u'Пациент'),
)

class Review(models.Model):
    reviewer_type = models.CharField(
        verbose_name = u'тип автора обзора',
        max_length = 30,
        choices = REVIEWER_TYPE_CHOICES
    )
    reviewer_post = models.CharField(
        verbose_name = u'должность',
        max_length = 200,
        blank = True,
        null = True
    )
    initials = models.CharField(
        verbose_name = u'ФИО',
        max_length = 200
    )
    email = models.CharField(
        verbose_name = u'e-mail',
        max_length = 200,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        blank = True,
        )
    phone = models.CharField(
        verbose_name = u'номер телефона',
        max_length = 200,
        blank = True,
    )
    review = models.TextField(
        verbose_name = u'обзор'
    )  
    image = ImageField(
        verbose_name = u'изображение',
        upload_to = file_path_reviews,
        blank = True
    )
    is_published = models.BooleanField(
        verbose_name = u'признак публикации'
    )

    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.initials

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'отзыв'
        verbose_name_plural = u'отзывы'

apps/siteblocks/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
import datetime
import os
from pytils.translit import translify
from django.db.models.signals import post_save
from apps.utils.managers import PublishedManager
from mptt.models import MPTTModel, TreeForeignKey, TreeManager

def image_path(self, instance, filename):
    filename = translify(filename).replace(' ', '_')
    return os.path.join('uploads', 'images/menu', filename)

class SiteMenu(MPTTModel):
    MENU_TYPE_CHOISES = (
        ('header','верхнее меню'),
        ('footer','нижнее меню'),
    )

    title = models.CharField(
        max_length = 150, 
        verbose_name = u'Название'
    )
    image = models.ImageField(
        verbose_name=u'Иконка',
        upload_to = image_path, 
        blank = True,
        null = True,
    )
    parent = TreeForeignKey(
        'self',
        verbose_name = u'Родительский раздел',
        related_name = 'children',
        blank = True,
        null = True,
    )
    menu_type = models.CharField(
        verbose_name = u'в каком меню показывать',
        max_length = 200,
        choices = MENU_TYPE_CHOISES
    )
    url = models.CharField(
        verbose_name = u'url', 
        max_length = 150, 
    )
    order = models.IntegerField(
        verbose_name = u'Порядок сортировки',
        default = 10,
        help_text = u'чем больше число, тем выше располагается элемент'
    )
    is_published = models.BooleanField(
        verbose_name=u'Опубликовано',
        default=True, 
    )

    objects = TreeManager()

    def save(self, *args, **kwargs):
        self.title = self.title.strip()
        self.url = self.url.strip()
        super(SiteMenu, self).save()

    class Meta:
        verbose_name =_(u'menu_item')
        verbose_name_plural =_(u'menu_items')
        ordering = ['-order']

    class MPTTMeta:
        order_insertion_by = ['order']

    def __unicode__(self):
        return self.title

type_choices = (
    (u'input',u'input'),
    (u'textarea',u'textarea'),
    (u'redactor',u'redactor'),
)

class Settings(models.Model):
    title = models.CharField(
        verbose_name = u'Название',
        max_length = 150,
    )
    name = models.CharField( 
        verbose_name = u'Служебное имя',
        max_length = 250,
    )
    value = models.TextField(
        verbose_name = u'Значение'
    )
    type = models.CharField(
        max_length=20,
        verbose_name=u'Тип значения',
        choices=type_choices
    )
    class Meta:
        verbose_name =_(u'site_setting')
        verbose_name_plural =_(u'site_settings')

    def __unicode__(self):
        return u'%s' % self.name

templates/pages/default.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block main %}
    <div class="main">
        <div class="content">
        <h1>{{ page.title }}</h1>
        {{ page.content|safe }}
        </div>
    </div>
{% endblock %}

templates/pages/index.html
{% extends "base.html" %}

{% load thumbnail %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}
    </div>
{% endblock %}

templates/pages/instructions.html
{% extends 'base.html' %}

{% block main %}
<!--MAIN-->
	<div class="main">
		<div class="content">
			<div class="content_l col">
				<h1>Как использовать самому</h1>
				
				<div class="text page_lead">
					{{instruction_top_text|safe}}
				</div>
				
				<div class="steps">
					<div class="side">
						<div class="arrpl arrpl_2">
							<h2 class="side_h">Инструкция по&nbsp;применению</h2>
						</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_1.png" alt="" /></div>
						<div class="step_num">1</div>
						<div class="step_name">4 капли из красного флакона</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_2.png" alt="" /></div>
						<div class="step_num">2</div>
						<div class="step_name">4 капли из жёлтого флакона</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_3.png" alt="" /></div>
						<div class="step_num">3</div>
						<div class="step_name">Взять мазок с поверхности миндалин и задней стенки глотки. Старайтесь не касаться  ватной палочкой языка, дёсен, нёба, зубов (она стерильна).</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_4.png" alt="" /></div>
						<div class="step_num">4</div>
						<div class="step_name">Покрутить ватную палочку с материалом 10 раз в пробирке и оставить на 1 минуту.</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_5.png" alt="" /></div>
						<div class="step_num">5</div>
						<div class="step_name">Отжать ватную палочку в раствор</div>
					</div>
					
					<div class="step">
						<div class="step_img"><img src="/media/img/step_6.png" alt="" /></div>
						<div class="step_num">6</div>
						<div class="step_name">Опустить тест-полоску в раствор стрелками вниз на 5 минут</div>
					</div>
				</div><!--/steps-->
			</div><!--/content_l-->
			
			<div class="content_r col">
				{% include 'shared/buy_box_aside.html' %}
				
				<div class="res_lnk"><a class="fancybox" href="#instructions_modal"><span>Как правильно считывать результат</span></a></div>
			</div><!--/content_r-->
				
			<div class="content_l col">
				<div class="video_study">
					<div class="side">
						<div class="arrpl arrpl_2">
							<h2 class="side_h">Обучающее видео</h2>
						</div>
					</div>
					
					<div class="video">
						<iframe width="561" height="342" src="{{ instructions_video }}" frameborder="0" allowfullscreen></iframe>
					</div>
				</div><!--/video_study-->
				
				<div class="cases">
					<div class="side">
						<div class="arrpl arrpl_2">
							<h2 class="side_h">Случаи из&nbsp;жизни</h2>
						</div>
					</div>
					
					<div class="case">
						<div class="case_img"><img src="/media/img/case_1.png" alt="" /></div>
						<h3 class="case_h">Дома</h3>
						<div class="case_des">Важно быть уверенным в правильности лечения</div>
					</div>
					
					<div class="case">
						<div class="case_img"><img src="/media/img/case_2.png" alt="" /></div>
						<h3 class="case_h">В отпуске</h3>
						<div class="case_des">Болезнь не должна испортить отдых</div>
					</div>
					
					<div class="case">
						<div class="case_img"><img src="/media/img/case_3.png" alt="" /></div>
						<h3 class="case_h">Важная ситуация</h3>
						<div class="case_des">Когда нет времени и каждый час на счету</div>
					</div>
				</div><!--/cases-->
			</div><!--/content_l-->
			
			<div class="content_r col">
				<div class="video_note">Удобен и может быть использован человеком без медицинского образования в домашних условиях</div>
			</div><!--/content_r-->
		</div><!--/content-->
		
	</div>
    <!--/MAIN-->
{% endblock %}
{% block modals %}
<div class="instructions_modal" id="instructions_modal">
	<div class="modal modal_blob">
		<div class="modal_header">
			<h2>Как правильно считывать результат</h2>
		</div><!--/modal_header-->
		
		<div class="modal_instruction"><img src="/media/img/instruction.png" alt="" /></div>
		{% if instructions_modal_text %}
		<div>{{ instructions_modal_text }}</div>
		{% endif %}
	</div>
</div>
{% endblock %}

templates/pages/page_content.html
{% if content %}
    {{ content|safe }}
{% endif %}

templates/pages/registration.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        <h1>{{ page.title }}</h1>
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}

    </div>
    <div class="classes2">
        <ul>
            <li><a href="#members">Регистрация пилотов</a></li>
            <li><a href="#guests">Регистрация зрителей</a></li>
        </ul>
    </div>
    <div class="subpage" id="members" style="display: none;">
        <div class="text text_page">
            {{ members.content|safe }}
        </div>
        {% if block_reg %}
            {{ block_reg|safe }}
        {% endif %}
    </div>
    <div class="subpage" id="guests" style="display: none;">
        <div class="text text_page">
            {{ guests.content|safe }}
        </div>
        <form action="#guests" method="post" class="guest_form">
        {% if send %}
            <p>Приглашение отправлено на Ваш адрес электронной почты.</p>
        {% else %}
            <div class="input"><label for="id_name">ФИО</label>{{ form.name }}{{ form.name.errors }}</div>
            <div class="input"><label for="id_phone">Телефон</label>{{ form.phone }}{{ form.phone.errors }}</div>
            <div class="input"><label for="id_email">E-mail</label>{{ form.email }}{{ form.email.errors }}</div>
            <div class="check"><label for="id_parking">{{ form.parking }} Требуется автопарковка</label></div>
            <div class="input">{{ form.captcha }}{{ form.captcha.errors }}</div>
            <div class="submit"><input style="font: 12px/15px 'Arial', sans-serif;" type="submit" value="Получить приглашение" /></div>
        {% endif %}
        </form>
    </div>

{% endblock %}