urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns

from apps.views import index, InstructionsView, SubscribeFormView
from apps.reviews.views import ReviewIndexView, ReviewListView, MoreReviewsView, ReviewFormView
from apps.capabilities.views import CapabilityListView 
from apps.messages.views import OrderFormView, \
                                PartnersView, PartnersDoctorsFormView, PartnersDrugstoresFormView, \
                                PatientsView, PatientsQFormView, PatientsSchoolFormView
from apps.publications.views import ArticleListView, ArticleView, NewsListView, NewsView, PublicationListView, PublicationView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^captcha/', include('captcha.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),
     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),
    # index
    (r'^$', index), 
    # reviews
    url(r'^reviews/$', ReviewIndexView.as_view(), name='reviews_url'),
    url(r'^reviews/patients/$', ReviewListView.as_view(), {'reviewer_type':'patient'}, name='patients_reviews_url'),
    url(r'^reviews/doctors/$', ReviewListView.as_view(), {'reviewer_type':'doctor'}, name='doctors_reviews_url'),
    url(r'^reviews/patients/more/$', MoreReviewsView.as_view(), {'reviewer_type':'patient'}, name='patients_more_url'),
    url(r'^reviews/doctors/more/$', MoreReviewsView.as_view(), {'reviewer_type':'doctor'}, name='doctors_more_url'),
    url(r'^reviews/patients/form/$', ReviewFormView.as_view()),
    url(r'^reviews/doctors/form/$', ReviewFormView.as_view()),
    # capabilities
    url(r'^capabilities/$', CapabilityListView.as_view(), name='capabilities_url'),
    # order form
    url(r'^order/$', OrderFormView.as_view(), name='order_url'),
    # instructions
    url(r'^instructions/$', InstructionsView.as_view(), name='instructions_url'),
    # for_patients
    url(r'^for_patients/$', PatientsView.as_view(), name='patients_url'),
    url(r'^for_patients/q_form/$', PatientsQFormView.as_view(), name='patients_q_url'),
    url(r'^for_patients/school_form/$', PatientsSchoolFormView.as_view(), name='patients_school_url'),
    # for_partners
    url(r'^for_partners/$', PartnersView.as_view(), name='partners_url'),
    url(r'^for_partners/doctors_form/$', PartnersDoctorsFormView.as_view(), name='partners_doctors_url'),
    url(r'^for_partners/clinics_form/$', PartnersDrugstoresFormView.as_view(), name='partners_drugstores_url'),
    # publications
    url(r'^newsboard/$', NewsListView.as_view(), name='news_list_url'),
    url(r'^articles/$', ArticleListView.as_view(), name='article_list_url'),
    url(r'^publications/$', PublicationListView.as_view(), name='publication_list_url'),
    url(r'^publications/(?P<id>\d)/$', PublicationView.as_view(), name='publication_url'),
    url(r'^newsboard/(?P<id>\d)/$', NewsView.as_view(), name='single_news_url'),
    url(r'^articles/(?P<id>\d)/$', ArticleView.as_view(), name='article_url'),
    # subscribe
    url(r'^subscribe/$', SubscribeFormView.as_view(), name='subscribe_url'),
)

urlpatterns += apps_urlpatterns

apps/places/models.py
# coding: utf-8
from datetime import datetime

from django.db import models

class City(models.Model):
    title = models.CharField(
        verbose_name = u'город',
        max_length = 100,
    )
    coordinates_center = models.CharField(
        verbose_name = u'центр координат',
        max_length = 300,
    )
    zoom = models.IntegerField(
        verbose_name = u'зум',
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = u'город'
        verbose_name_plural = u'города'


class Clinic(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'клиника'
        verbose_name_plural = u'клиники'


class Drugstore(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'аптека'
        verbose_name_plural = u'аптеки'


class Lab(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'лаборатория'
        verbose_name_plural = u'лаборатории'
        

class Branch(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'филиал'
        verbose_name_plural = u'филиалы'

templates/_contacts_map.html
{% for city in city_list %}
    {% if forloop.first %}
    <div id="contacts_map_{{city.id}}" style="width: 100%; height: 100%;"></div>
    {% else %}
    <div id="contacts_map_{{city.id}}" style="width: 100%; height: 100%; display:none;"></div>
    {% endif %}
{% endfor %}
<script>
var ContactsMap = function(){
    {% for city in city_list %}
    var contactsMap_{{city.id}};
    {% if forloop.first %}
    var currentMap;
    {% endif %}
    function initHeaderMap_{{city.id}}(){     
        contactsMap_{{city.id}} = new ymaps.Map ("contacts_map_{{city.id}}", {
            center: [{{city.coordinates_center}}],
            zoom: {{city.zoom}},
        });
        contactsMap_{{city.id}}.controls.add(
           new ymaps.control.ZoomControl()
        );
        currentMap = contactsMap_{{city.id}};
        {% for branch in city.branch_set.all %}
            var myPlacemark_{{branch.id}} = new ymaps.Placemark(
                [{{branch.coordinates}}],
                {
                    content: '{{branch.id}}',
                    balloonContent: '<p>{{branch.title}}</p><p>{{branch.address}}</p>'
                });
            contactsMap_{{city.id}}.geoObjects.add(myPlacemark_{{branch.id}});
        {% endfor %}
    }
    {% if forloop.first %}
    var currentCity;
    $('.contacts-fancybox').fancybox({
        padding: 0,
        type: 'inline',
        tpl : {
            closeBtn : '<div class="blob_modal_close"></div>'
        },
        beforeShow: function(){
            ymaps.ready(initHeaderMap_{{city.id}});
            currentCity = {{city.id}};
        },
        beforeClose: function(){
            currentMap.destroy();
        }
    });
    {% endif %}
{% endfor %}
{% for city in city_list %}
    $('#contacts_map_link_{{city.id}}').on('click', function(){
        $('.branches_'+currentCity).hide();
        $('#contacts_map_'+currentCity).hide();
        alert('asd');
        currentMap.destroy();
        $('#contacts_map_link_'+currentCity).parent('li').removeClass('curr');
        $('#contacts_map_{{city.id}}').show();
        $('.branches_{{city.id}}').show();
        $('#contacts_map_link_{{city.id}}').parent('li').addClass('curr');
        ymaps.ready(initHeaderMap_{{city.id}});
        currentCity = {{city.id}};
    });
{% endfor %}
};
ContactsMap();
</script>

templates/_footer.html
{% load siteblocks_extras %}
<!--FOOTER-->
<div class="footer_out">
<div class="footer">
    <div id="copyright" class="col">
        <p>© 2010–{{ now.year }}</p>
        <p>ООО «Сатиус»</p>
        <a href="http://satius.su/"><img src="/media/img/logo_satius.gif" width="72" height="25"></a>
    </div>
    
    <div class="footer_menu col">
        <ul>
        	<li><a id="friends_modal_link" class="fancybox" href="#friend_modal">Посоветовать друзьям</a></li>
        	<li><a id="subscribe_link" class="fancybox" href="#subscribe_modal">Подписаться на новости</a></li>
            <li><a id="subscribe_link" href="{{ youtube_link }}">Канал на youtube</a></li>
        	<li><a href="{% url news_list_url %}">Пресс-центр</a></li>
        </ul>
        <p>Сайт разработан в студии <a href="http://octoberweb.ru/" title="Разработка сайта — студия OctoberWeb">«<u>OctoberWeb</u>»</a></p>
    </div><!--/footer_menu-->
    
    <div class="footer_soc">
        {{ like_widget_code|safe }}
    </div>
</div>
</div>
<!--/FOOTER-->
{% include '_footer_modals.html' %}

templates/_footer_modals.html
<div class="friends_modal" id="friend_modal">
    <div class="modal modal_blob">
        <div class="modal_header">
            <h2>Посоветовать друзьям</h2>
        </div><!--/modal_header-->
        
        {{ facebook_widget_code|safe }}<div id="vk_groups"></div>

    </div>
</div><!--/modal-->

<div class="subscribe_modal" id="subscribe_modal">
    {% include '_new_subscribe_form.html' %}
</div><!--/modal-->
{{ vk_widget_code|safe }}

templates/_header.html
{% load siteblocks_extras %}
<!--HEADER-->
<div class="header">
    <a id="logo_box" href="/" title="Стрептатест"><img id="logo" src="/media/img/logo.png" alt="Стрептатест" width="581" height="69" /></a>
    
    <p class="header_info">Умный экспресс-тест для защиты здоровья всей семьи</p>
    
    <div class="header_contacts">
        <p>Горячая линия</p>
        {% if contacts %}
        <div class="tel"><span>+7</span> {{ contacts }}</div>
        {% endif %}
        <p><a href="#contact_map_modal" class="header_contacts_lnk contacts-fancybox">Как нас найти</a></p>
    </div><!--/header_contacts-->
    <div class="header_menu">
        {% header_menu request.path %}
    </div><!--/menu-->
</div>
<!--/HEADER-->

<div class="contact_map_modal" id="contact_map_modal">
<div class="modal_blob">
    <div class="h_line">
        <h2>Как нас найти</h2>
        <div class="hormenu col">
            <ul>
                {% for city in city_list %}
                    {% if forloop.first %}
                    <li class="curr">
                    <a id="contacts_map_link_{{city.id}}" class="cont_link">{{city.title}}</a>
                    <img src="/media/img/hormenu_arr.png"/>           
                    {% else %}
                    <li>
                    <a id="contacts_map_link_{{city.id}}" class="cont_link" href="#">{{city.title}}</a>
                    <img src="/media/img/hormenu_arr.png"/>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div><!--/hormenu-->
    </div><!--/modal_header-->

    <div class="col">
        <div class="map" style="width: 800px; height: 600px;">
            {% for city in city_list %}
                {% if forloop.first %}
                <div id="contacts_map_{{city.id}}" class="cont_map" style="width: 100%; height: 100%;"></div>
                {% else %}
                <div id="contacts_map_{{city.id}}" class="cont_map" style="width: 100%; height: 100%; display:none;"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="col contacts_branches">
    {% for city in city_list %}
        {% if forloop.first %}
        <div class="cont_branch branches_{{city.id}}">
        {% else %}
        <div class="cont_branch branches_{{city.id}}" style="display:none;">
        {% endif %}
            {% for branch in city.branch_set.all %}
            <div class="branch">
                <p>{{ branch.city }}</p>
                <p>{{ branch.address }}</p>
                <p><span class="phone">{{ branch.phone }}</span></p>
            </div>
            {% endfor %}
        </div>
    {% endfor %}
    </div>
    <div class="modal_shade"></div>
</div>
</div>
<script>
var ContactsMap = function(){
    {% for city in city_list %}
    var contactsMap_{{city.id}};
    {% if forloop.first %}
    var currentContactsMap;
    {% endif %}
    function initHeaderMap_{{city.id}}(){     
        contactsMap_{{city.id}} = new ymaps.Map ("contacts_map_{{city.id}}", {
            center: [{{city.coordinates_center}}],
            zoom: {{city.zoom}},
        });
        contactsMap_{{city.id}}.controls.add(
           new ymaps.control.ZoomControl()
        );
        currentContactsMap = contactsMap_{{city.id}};
        {% for branch in city.branch_set.all %}
            var myPlacemark_{{branch.id}} = new ymaps.Placemark(
                [{{branch.coordinates}}],
                {
                    content: '{{branch.id}}',
                    balloonContent: '<p>{{branch.title}}</p><p>{{branch.address}}</p>'
                });
            contactsMap_{{city.id}}.geoObjects.add(myPlacemark_{{branch.id}});
        {% endfor %}
    }
    {% if forloop.first %}
    var currentContactsCity;
    $('.contacts-fancybox').fancybox({
        padding: 0,
        type: 'inline',
        tpl : {
            closeBtn : '<div class="blob_modal_close"></div>'
        },
        beforeShow: function(){
            ymaps.ready(initHeaderMap_{{city.id}});
            currentContactsCity = {{city.id}};
        },
        beforeClose: function(){
            currentContactsMap.destroy();
            $('.cont_branch').hide();
            $('.cont_map').hide();
            $('.cont_link').parent('li').removeClass('curr');
            $('#contacts_map_{{city.id}}').show();
            $('.branches_{{city.id}}').show();
            $('#contacts_map_{{city.id}}').show();
            $('.branches_{{city.id}}').show();
            $('#contacts_map_link_{{city.id}}').parent('li').addClass('curr');
        }
    });
    {% endif %}
{% endfor %}
{% for city in city_list %}
    $('#contacts_map_link_{{city.id}}').on('click', function(){
        $('.branches_'+currentContactsCity).hide();
        $('#contacts_map_'+currentContactsCity).hide();
        currentContactsMap.destroy();
        $('#contacts_map_link_'+currentContactsCity).parent('li').removeClass('curr');
        $('#contacts_map_{{city.id}}').show();
        $('.branches_{{city.id}}').show();
        $('#contacts_map_link_{{city.id}}').parent('li').addClass('curr');
        ymaps.ready(initHeaderMap_{{city.id}});
        currentContactsCity = {{city.id}};
    });
{% endfor %}
};
ContactsMap();
</script>

templates/_header_menu.html
{% load mptt_tags %}

<ul>
{% recursetree menu %}
    {% if node.url == current %}
    <li class="curr">
    {% else %}
    <li>
    {% endif %}<a href="{{ node.url }}">{{ node.title }}</a></li>
{% endrecursetree %}
</ul>

templates/_new_subscribe_form.html
<div class="modal modal_blob">
    <div class="modal_header">
        <h2>Подписаться на новости</h2>
    </div><!--/modal_header-->

    <form class="subscribe_form review_form" method="post" action="{% url subscribe_url %}">
        {% csrf_token %}
        <div class="review_form_inputs">
        	
            <div class="form_line">
        		<label class="required">ФИО:</label>
        		<input class="inpt" type="text" name="initials" value="{{subscribe_form.initials.value|default_if_none:''}}" />
                <span class="form-text-error">{{subscribe_form.initials.errors}}</span>
        	</div>

            <div class="form_line">
                <label class="required">E-mail:</label>
                <input class="inpt" type="text" name="email" value="{{subscribe_form.email.value|default_if_none:''}}" />
                <span class="form-text-error">{{subscribe_form.email.errors}}</span>
            </div>

            <div class="form_line form_captcha captha_review">
                {{ subscribe_form.captcha }}
                <span class="form-text-error">{{ subscribe_form.captcha.errors }}</span>
            </div>

            <div class="btn_zs"><div class="btn_zs_in"><input type="submit" value="Отправить отзыв" /></div></div>
        </div>
    </form>
</div>

templates/base.html
{% load siteblocks_extras %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/media/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/media/css/jquery-ui-1.9.2.custom.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/media/css/jquery.fancybox.css" />
    <!--[if lte IE 8]><link rel="stylesheet" type="text/css" media="screen" href="/media/css/ie.css" /><![endif]-->
    <script type="text/javascript" src="/media/js/jquery.js"></script>
    <script type="text/javascript" src="/media/js/jquery.bxSlider.min.js"></script>
    <script type="text/javascript" src="/media/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/media/js/script.js"></script>
    <script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU&coordorder=longlat" type="text/javascript"></script>
    <!-- Put this script tag to the <head> of your page -->
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?74"></script>
    <script type="text/javascript" src="/media/js/jquery.maskedinput-1.3.min.js"></script>
    <script type="text/javascript" src="/media/js/jquery.fullscreen-min.js"></script>
    <script type="text/javascript" src="/media/js/jquery.fancybox.js"></script>
    <title>
        {% block title %}{% endblock %}
        {{ site_name }}
    </title>
    {% block head %}{% endblock %}
</head>

<body>
<div class="wrapper {% block wrapper_class %}{% endblock %}">
<div class="page">
{% include '_header.html' %}
{% block main %}{% endblock %}
</div>
{% block modals%}{% endblock %}
</div>
{% include '_footer.html' %}
</body>
</html>