urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns

from apps.views import index, InstructionsView, SubscribeFormView
from apps.reviews.views import ReviewIndexView, ReviewListView, MoreReviewsView, ReviewFormView
from apps.capabilities.views import CapabilityListView 
from apps.messages.views import OrderFormView, \
                                PartnersView, PartnersDoctorsFormView, PartnersDrugstoresFormView, \
                                PatientsView, PatientsQFormView, PatientsSchoolFormView
from apps.publications.views import ArticleListView, ArticleView, NewsListView, NewsView, PublicationListView, PublicationView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^captcha/', include('captcha.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),
     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),
    # index
    (r'^$', index), 
    # reviews
    url(r'^reviews/$', ReviewIndexView.as_view(), name='reviews_url'),
    url(r'^reviews/patients/$', ReviewListView.as_view(), {'reviewer_type':'patient'}, name='patients_reviews_url'),
    url(r'^reviews/doctors/$', ReviewListView.as_view(), {'reviewer_type':'doctor'}, name='doctors_reviews_url'),
    url(r'^reviews/patients/more/$', MoreReviewsView.as_view(), {'reviewer_type':'patient'}, name='patients_more_url'),
    url(r'^reviews/doctors/more/$', MoreReviewsView.as_view(), {'reviewer_type':'doctor'}, name='doctors_more_url'),
    url(r'^reviews/patients/form/$', ReviewFormView.as_view()),
    url(r'^reviews/doctors/form/$', ReviewFormView.as_view()),
    # capabilities
    url(r'^capabilities/$', CapabilityListView.as_view(), name='capabilities_url'),
    # order form
    url(r'^order/$', OrderFormView.as_view(), name='order_url'),
    # instructions
    url(r'^instructions/$', InstructionsView.as_view(), name='instructions_url'),
    # for_patients
    url(r'^for_patients/$', PatientsView.as_view(), name='patients_url'),
    url(r'^for_patients/q_form/$', PatientsQFormView.as_view(), name='patients_q_url'),
    url(r'^for_patients/school_form/$', PatientsSchoolFormView.as_view(), name='patients_school_url'),
    # for_partners
    url(r'^for_partners/$', PartnersView.as_view(), name='partners_url'),
    url(r'^for_partners/doctors_form/$', PartnersDoctorsFormView.as_view(), name='partners_doctors_url'),
    url(r'^for_partners/clinics_form/$', PartnersDrugstoresFormView.as_view(), name='partners_drugstores_url'),
    # publications
    url(r'^newsboard/$', NewsListView.as_view(), name='news_list_url'),
    url(r'^articles/$', ArticleListView.as_view(), name='article_list_url'),
    url(r'^publications/$', PublicationListView.as_view(), name='publication_list_url'),
    url(r'^publications/(?P<id>\d)/$', PublicationView.as_view(), name='publication_url'),
    url(r'^newsboard/(?P<id>\d)/$', NewsView.as_view(), name='single_news_url'),
    url(r'^articles/(?P<id>\d)/$', ArticleView.as_view(), name='article_url'),
    # subscribe
    url(r'^subscribe/$', SubscribeFormView.as_view(), name='subscribe_url'),
)

urlpatterns += apps_urlpatterns

apps/places/models.py
# coding: utf-8
from datetime import datetime

from django.db import models

class City(models.Model):
    title = models.CharField(
        verbose_name = u'город',
        max_length = 100,
    )
    coordinates_center = models.CharField(
        verbose_name = u'центр координат',
        max_length = 300,
    )
    zoom = models.IntegerField(
        verbose_name = u'зум',
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = u'город'
        verbose_name_plural = u'города'


class Clinic(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'клиника'
        verbose_name_plural = u'клиники'


class Drugstore(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'аптека'
        verbose_name_plural = u'аптеки'


class Lab(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'лаборатория'
        verbose_name_plural = u'лаборатории'
        

class Branch(models.Model):
    city = models.ForeignKey(
        'City',
        verbose_name = u'город',
    )
    title = models.CharField(
        verbose_name = u'название',
        max_length = 100,
    )
    address = models.CharField(
        verbose_name = u'адрес',
        max_length = 400,
    )
    phone_code = models.CharField(
        verbose_name = u'код телефона',
        max_length = 100,
        )
    phone = models.CharField(
        verbose_name = u'телефон',
        max_length = 300,
        blank = True,
    )
    coordinates = models.CharField(
        verbose_name = u'координаты',
        max_length = 300,
    )
    # timestamps
    created_at = models.DateTimeField(
        verbose_name = u'дата создания',
        default = datetime.now(),
        editable = False,
    )
    updated_at = models.DateTimeField(
        verbose_name = u'дата изменения',
        auto_now = True,
        default = datetime.now(),
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', '-id',]
        verbose_name = u'филиал'
        verbose_name_plural = u'филиалы'

apps/messages/templates/_drugstores_map.html
{% for city in city_list %}
    {% if forloop.first %}
        <div id="drugstores_map_{{city.id}}" style="width:100%;height:100%;"></div>
    {% else %}
        <div id="drugstores_map_{{city.id}}" style="width:100%;height:100%;display:none;"></div>
    {% endif %}
{% endfor %}
<script>
var DrugstoresMap = function(){
{% for city in city_list %}
    var drugstoresMap_{{city.id}};
    var currentMap;
    function init_{{city.id}}(){     
        drugstoresMap_{{city.id}} = new ymaps.Map ("drugstores_map_{{city.id}}", {
            center: [{{city.coordinates_center}}],
            zoom: {{city.zoom}},
        });
        drugstoresMap_{{city.id}}.controls.add(
           new ymaps.control.ZoomControl()
        );
        var button_{{city.id}} = new ymaps.control.Button({
            data: {
                image: '/media/img/icon-fullscreen.png',
                content: '<img class="fullscreen-button_{{city.id}}"/>',
                title:'Разворачивать карту на весть экран'
            }
        }, {
            selectOnClick: true
        });
        button_{{city.id}}.events.add(['select', 'deselect'], function (e) {
            if(button_{{city.id}}.isSelected()) {
                console.log('selected');
                $("#drugstores_map_{{city.id}}").fullScreen(true);
            }
            else {
                $("#drugstores_map_{{city.id}}").fullScreen(false);
            }
        });
        drugstoresMap_{{city.id}}.controls.add(button_{{city.id}}, { top : 5, left : 5 });               
        currentMap = drugstoresMap_{{city.id}};
        {% for drugstore in city.drugstore_set.all %}
            var myPlacemark_{{drugstore.id}} = new ymaps.Placemark(
                [{{drugstore.coordinates}}],
                {
                    content: '{{drugstore.id}}',
                    balloonContent: '<p>{{drugstore.title}}</p><p>{{drugstore.address}}</p>'
                },{
                    iconImageHref: '/media/img/ic_map_apt.png', // картинка иконки
                    iconImageSize: [30, 25], // размеры картинки
                    iconImageOffset: [-6,-12] // смещение картинки
                });
            drugstoresMap_{{city.id}}.geoObjects.add(myPlacemark_{{drugstore.id}});
        {% endfor %}
    }
    {% if forloop.first %}
    ymaps.ready(init_{{city.id}});
    var currentCity = {{city.id}};
    {% endif %}
{% endfor %}
{% for city in city_list %}
    $('#drugstores_map_link_{{city.id}}').on('click', function(){
        $('#drugstores_map_'+currentCity).hide();
        currentMap.destroy();
        $('#drugstores_map_link_'+currentCity).parent('li').removeClass('curr');
        $('#drugstores_map_{{city.id}}').show();
        $('#drugstores_map_link_{{city.id}}').parent('li').addClass('curr');
        ymaps.ready(init_{{city.id}});
        currentCity = {{city.id}};
    });
{% endfor%}
};
DrugstoresMap();
</script>

apps/messages/templates/_new_patients_q_form.html
<div class="modal modal_blob">
    <div class="modal_header">
        <h2 class="col">Задать вопрос</h2>
    </div><!--/modal_header-->

    <form class="patients-question-form review_form" method="post" action="{% url patients_q_url %}">
        {% csrf_token %}
        <div class="review_form_inputs">
        	
            <div class="form_line">
        		<label class="required">ФИО:</label>
        		<input class="inpt" type="text" name="initials" value="{{q_form.initials.value|default_if_none:''}}" />
                <span class="form-text-error">{{q_form.initials.errors}}</span>
        	</div>

            <div class="form_line">
                <label class="required">E-mail:</label>
                <input class="inpt" type="text" name="email" value="{{q_form.email.value|default_if_none:''}}" />
                <span class="form-text-error">{{q_form.email.errors}}</span>
                {% if q_form.allow_mailings.value == 0 %}
                    <div class="mail_checkbox">Получать информационную рассылку на этот e-mail</div>
                    <input style="display:none;" class="inpt mail_inpt" type="checkbox" name="allow_mailings"/>
                {% else %}
                    <div class="mail_checkbox mail_checked">Получать информационную рассылку на этот e-mail</div>
                    <input style="display:none;" class="inpt mail_inpt" type="checkbox" name="allow_mailings" checked="checked"/>
                {% endif %}
            </div>

            <div class="form_line">
                <label class="required">Ваш вопрос:</label>
                <textarea name="question" class="txtr" rows="0" cols="0">{{q_form.question.value|default_if_none:''}}</textarea>
                <span class="form-text-error">{{q_form.question.errors}}</span>
            </div>
            <div class="form_line form_captcha captha_review">
                {{ q_form.captcha }}<span class="input_note">Введите текст, который вы видите на картинке слева от поля</span>
                <span class="form-text-error">{{ q_form.captcha.errors }}</span>
            </div>

            <div class="btn_zs"><div class="btn_zs_in"><input type="submit" value="Отправить отзыв" /></div></div>
        </div>
    </form>
</div>

apps/messages/templates/_new_patients_school_form.html
<div class="modal modal_blob">
    <div class="modal_header">
        <h2 class="col">Записаться в школу пациентов</h2>
    </div><!--/modal_header-->

    <form class="patients-school-form review_form" method="post" action="{% url patients_school_url %}">
        {% csrf_token %}
        <div class="review_form_inputs">
            
            <div class="form_line">
                <label class="required">ФИО:</label>
                <input class="inpt" name="initials" type="text" value="{{school_form.initials.value|default_if_none:''}}" />
                <span class="form-text-error">{{school_form.initials.errors}}</span>
            </div>

            <div class="form_line">
                <label class="required">E-mail:</label>
                <input class="inpt" type="text" name="email" value="{{school_form.email.value|default_if_none:''}}" />
                <span class="form-text-error">{{school_form.email.errors}}</span>
                {% if school_form.allow_mailings.value == 0 %}
                    <div class="mail_checkbox">Получать информационную рассылку на этот e-mail</div>
                    <input style="display:none;" class="inpt mail_inpt" type="checkbox" name="allow_mailings"/>
                {% else %}
                    <div class="mail_checkbox mail_checked">Получать информационную рассылку на этот e-mail</div>
                    <input style="display:none;" class="inpt mail_inpt" type="checkbox" name="allow_mailings" checked="checked"/>
                {% endif %}
            </div>

            <div class="form_line">
                <label class="required">Телефон:</label>
                <strong class="inpt_tel_label">+7</strong> <input class="inpt inpt_code" type="text" name="phone_code" value="{{ school_form.phone_code.value|default_if_none:"" }}" style="width:30px;"/>
                <input class="inpt inpt_tel inpt_tel_school_form" type="text" name="phone" value="{{ school_form.phone.value|default_if_none:"" }}"/>
                <span class="form-text-error">{{school_form.phone_code.errors}} {{school_form.phone.errors}}</span>
            </div>

            <div class="form_line">
                <label class="required">Цель записи:</label>
                <textarea name="message" class="txtr" rows="0" cols="0">{{school_form.message.value|default_if_none:''}}</textarea>
                <span class="form-text-error">{{school_form.message.errors}}</span>
            </div>
            <div class="form_line form_captcha captha_review">
                {{ school_form.captcha }}<span class="input_note">Введите текст, который вы видите на картинке слева от поля</span>
                <span class="form-text-error">{{ school_form.captcha.errors }}</span>
            </div>

            <div class="btn_zs"><div class="btn_zs_in"><input type="submit" value="Отправить отзыв" /></div></div>
        </div>
    </form>
</div>

apps/messages/templates/_patients_map.html
{% for city in city_list %}
    {% if forloop.first %}
        <div id="patients_map_{{city.id}}" style="width:100%;height:100%;"></div>
    {% else %}
        <div id="patients_map_{{city.id}}" style="width:100%;height:100%;display:none;"></div>
    {% endif %}
{% endfor %}
<script>
var PatientsMap = function(){
{% for city in city_list %}
    var patientsMap_{{city.id}};
    var currentMap;
    function init_{{city.id}}(){     
        patientsMap_{{city.id}} = new ymaps.Map ("patients_map_{{city.id}}", {
            center: [{{city.coordinates_center}}],
            zoom: {{city.zoom}},
        });
        patientsMap_{{city.id}}.controls.add(
           new ymaps.control.ZoomControl()
        );
        currentMap = patientsMap_{{city.id}};
        var button_{{city.id}} = new ymaps.control.Button({
            data: {
                image: '/media/img/icon-fullscreen.png',
                content: '<img class="fullscreen-button_{{city.id}}"/>',
                title:'Разворачивать карту на весть экран'
            }
        }, {
            selectOnClick: true
        });
        button_{{city.id}}.events.add(['select', 'deselect'], function (e) {
            if(button_{{city.id}}.isSelected()) {
                console.log('selected');
                $("#patients_map_{{city.id}}").fullScreen(true);
            }
            else {
                $("#patients_map_{{city.id}}").fullScreen(false);
            }
        });
        patientsMap_{{city.id}}.controls.add(button_{{city.id}}, { top : 5, left : 5 });
        {% for drugstore in city.drugstore_set.all %}
            var myPlacemark_drug_{{drugstore.id}} = new ymaps.Placemark(
                [{{drugstore.coordinates}}],
                {
                    content: '{{drugstore.id}}',
                    balloonContent: '<p>{{drugstore.title}}</p><p>{{drugstore.address}}</p>'
                },{
                    iconImageHref: '/media/img/ic_map_apt.png', // картинка иконки
                    iconImageSize: [30, 25], // размеры картинки
                    iconImageOffset: [-6,-12] // смещение картинки
                });
            patientsMap_{{city.id}}.geoObjects.add(myPlacemark_drug_{{drugstore.id}});
        {% endfor %}
        {% for lab in city.lab_set.all %}
            var myPlacemark_lab_{{lab.id}} = new ymaps.Placemark(
                [{{lab.coordinates}}],
                {
                    content: '{{lab.id}}',
                    balloonContent: '<p>{{lab.title}}</p><p>{{lab.address}}</p>'
                },{
                    iconImageHref: '/media/img/ic_map_lab.png', // картинка иконки
                    iconImageSize: [30, 25], // размеры картинки
                    iconImageOffset: [-6,-12] // смещение картинки
                });
            patientsMap_{{city.id}}.geoObjects.add(myPlacemark_lab_{{lab.id}});
        {% endfor %}
    }
    {% if forloop.first %}
    ymaps.ready(init_{{city.id}});
    var currentCity = {{city.id}};
    {% endif %}
{% endfor %}
{% for city in city_list %}
    $('#patients_map_link_{{city.id}}').on('click', function(){
        $('#patients_map_'+currentCity).hide();
        currentMap.destroy();
        $('#patients_map_link_'+currentCity).parent('li').removeClass('curr');
        $('#patients_map_{{city.id}}').show();
        $('#patients_map_link_{{city.id}}').parent('li').addClass('curr');
        ymaps.ready(init_{{city.id}});
        currentCity = {{city.id}};
    });
{% endfor %}
}
PatientsMap();
</script>

apps/messages/templates/order.html
{% extends 'base.html' %}
{% load pymorphy_tags %}

{% block main %}
<!--MAIN-->
	<div class="main">
		<div class="content">
			<div class="content_l col">
				<h1>Оформление заказа</h1>
				
				<div class="text page_lead">
					<p>Заказать экспресс-тест можно прямо на сайте. В удобное для вас время товар доставят по указанному адресу. Оплатить можно наличными или карточкой при получении.</p>
				</div>
				<form class="order_form" action="{% url order_url %}" method="post">
					{% csrf_token %}
					{% include '_order_form.html' %}
				</form>
			</div><!--/content_l-->
			
			<div class="content_r col">
				<div class="right_pl">
					<div class="right_pl_num">{{ drugstore_count }}</div>
					<p><strong>{{ 'аптека'|plural:drugstore_count }}</strong></p>
					<p>продают Стрептатест</p>
					<p><a class="dot" href="#map">смотреть на карте</a></p>
					<div class="arr_b"><img src="/media/img/arr_b.png" alt="" /></div>
				</div>
			</div><!--/content_r-->
				
			<div class="content_l col">
				<div class="h_line h_line2">
					<h2 class="col">Аптеки</h2>
					{% if city_list|length > 1 %}
					<div class="hormenu col">
						<ul>
							{% for city in city_list %}
								{% if forloop.first %}
								<li class="curr"><a id="drugstores_map_link_{{city.id}}">{{city.title}}</a><img src="/media/img/hormenu_arr.png"/></li>
								{% else %}
								<li><a id="drugstores_map_link_{{city.id}}" href="javascript:void(0)">{{city.title}}</a><img src="/media/img/hormenu_arr.png"/></li>
								{% endif %}
							{% endfor %}
						</ul>
					</div><!--/hormenu-->
					{% endif %}
				</div>
			</div><!--/content_l-->
			
			<div class="content_r col">
				<div class="up"><a href="#"><span class="dot">К оформлению заказа</span></a></div>
			</div><!--/content_r-->
		</div><!--/content-->

		<div id="map" class="map_zl">
			{% include '_drugstores_map.html' %}
		</div><!--/map_zl-->	
	</div>
    <!--/MAIN-->
{% endblock %}

apps/messages/templates/patients.html
{% extends 'base.html' %}
{% load pymorphy_tags %}

{% block main %}
<!--MAIN-->
	<div class="main">
		<div class="content">
			<div class="content_l col">
				<h1>Пациентам</h1>
				
				<div class="text page_lead">
					<p>Унитарное государство важно представляет собой онтологический кризис легитимности, что неминуемо повлечет эскалацию напряжения в стране. Политическое учение Руссо взаимно. Референдум, на первый взгляд, предсказуем.</p>
				</div>
				
				<div class="h_line">
					<h2>Аптеки и лаборатории</h2>
					{% if city_list|length > 1 %}
					<div class="hormenu col">
						<ul>
							{% for city in city_list %}
								{% if forloop.first %}
								<li class="curr"><a id="patients_map_link_{{city.id}}">{{city.title}}</a><img src="/media/img/hormenu_arr.png"/></li>
								{% else %}
								<li><a id="patients_map_link_{{city.id}}" href="javascript:void(0)">{{city.title}}</a><img src="/media/img/hormenu_arr.png"/></li>
								{% endif %}
							{% endfor %}
						</ul>
					</div><!--/hormenu-->
					{% endif %}
				</div>
				
				<div class="patients_map">
					<div class="map_legend side">
						<div class="map_legend_item_1">Аптеки, в которых продается Стрептатест</div>
						<div class="map_legend_item_2">Лаборатории</div>
					</div>
					<div class="map">
						{% include '_patients_map.html' %}
					</div>
				</div><!--/patients_map-->
				
				<div class="patients_school">
					<div class="side">
						<div class="arrpl arrpl_2">
							<h2 class="side_h">Школа пациентов</h2>
							<div class="arrpl_img"><img src="/media/img/side_people.png" alt="" /></div>
						</div>
					</div>
					
					<div class="text text_page">
						<p>Описание школы пациентов, зачем она существует, зачем она нужна, кто в ней участвует, какие проходят семинары. Какой толк от участия.</p>
						<p>Надо сказать, что механизм власти неравномерен. Культ личности определяет доиндустриальный тип политической культуры, указывает в своем исследовании К.Поппер. Как писал С.Хантингтон, структура политической науки символизирует континентально-европейский тип политической культуры, что может привести к военно-политической и идеологической конфронтации с Японией. Натуралистическая парадигма вероятна.</p>
					</div>
					
					<div class="patients_school_submit">
						<div class="btn_blue"><div class="btn_blue_in"><a class="patients-school-form-link fancybox" href="#patients_school_form_modal">Записаться</a></div></div>
						<em>Будьте в курсе всех мероприятий</em>
					</div>
				</div><!--/patients_school-->
			</div><!--/content_l-->
			
			<div class="content_r col">
				{% include 'shared/buy_box_aside.html' %}
				
				<div class="articles_block">
					<div class="block_name">Статьи</div>
					{% for article in last_articles %}
					<div class="article_block">
						<h3><a href="{% url article_url article.id %}">{{ article.title }}</a></h3>
						<p>{{ article.text|truncatewords:7 }}</p>
					</div>
					{% endfor %}
					{% if articles_more_count > 2 %}
					<div><a href="{% url article_list_url %}">Еще {{ articles_more_count }} {{ 'статья'|plural:articles_more_count }}</a></div>
					{% endif %}
				</div><!--/articles_block-->
				
				<div class="side_pl" style="margin: 0;">
					<p>Бесплатная консультация нашего специалиста</p>
					<div class="btn_blue"><div class="btn_blue_in"><a class="patients-q-form-link fancybox" href="#patients_question_form_modal">Задать вопрос</a></div></div>
				</div>

			</div><!--/content_r-->
				
				
		</div><!--/content-->
		
	</div>
    <!--/MAIN-->
{% endblock %}
{% block modals%}
	<div class="patients_question_form_modal" id="patients_question_form_modal">
		{% include '_new_patients_q_form.html' %}
	</div>
	<div class="patients_school_form_modal" id="patients_school_form_modal">
		{% include '_new_patients_school_form.html' %}
	</div>
{% endblock %}

apps/messages/templates/user_message_template.html
<p>
    <h2>{{ site_name }} - Ответ на ваш вопрос</h2>
    <hr>
    <p>Дата: {{ saved_object.pub_date }}</p>
    <p>Имя: {{ saved_object.name }}</p>
    <p>Email: {{ saved_object.email }}</p>
    <p>Вопрос: {{ saved_object.question }}</p>
    <hr>
    <p>Дата ответа:{{ saved_object.ans_date }}</p>
    <p>Автор:{{ saved_object.author }}</p>
    <p>Ответ:<br>{{ saved_object.answer|safe }}</p>
</p>